
modLoader='javafml'
loaderVersion='[32,)'
license='MIT'
issueTrackerURL='https://github.com/necauqua/Cleanse/issues'

[[mods]]
modId='cleanse'
version='${file.jarVersion}'
displayName='Cleanse'
logoFile='logo.png'
updateJSONURL='https://raw.githubusercontent.com/wiki/necauqua/cleanse/updates.json'
displayURL='https://www.curseforge.com/minecraft/mc-mods/cleanse'
credits='People from my discord who keep me entertained and remind to have a level of productivity that is not zero'
authors='necauqua'
description="Small clientside mod that helps to fix the 'big modpack chat spam' issue"

[[dependencies.cleanse]]
modId='forge'
mandatory=true
versionRange='[32,)'
ordering='NONE'
side='CLIENT'
