modLoader = 'javafml'
loaderVersion = '[41,)'
license = 'MIT'
issueTrackerURL = 'https://github.com/necauqua/Cleanse/issues'

[[mods]]
modId = 'cleanse'
version = '${file.jarVersion}'
displayName = 'Cleanse'
logoFile = 'logo.png'
updateJSONURL = 'https://raw.githubusercontent.com/wiki/necauqua/cleanse/updates.json'
displayURL = 'https://modrinth.com/mod/cleanse'
credits = 'People from my discord who keep me entertained and remind to have a level of productivity that is not zero'
authors = 'necauqua'
description = "Small clientside mod that helps to fix the 'big modpack chat spam' issue"

[[dependencies.cleanse]]
modId = 'forge'
mandatory = true
versionRange = '[41,)'
ordering = 'NONE'
side = 'BOTH'

[[dependencies.cleanse]]
modId = 'minecraft'
mandatory = true
versionRange = '[1.19,1.20)'
ordering = 'NONE'
side = 'BOTH'
